name: Hexo CICD

on: # 监视 `hexo`分支
  push:
      branches:
      - hexo

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}
      - uses: yrpang/github-actions-hexo@master
        with:
          deploykey: ${{secrets.DEPLOY_KEY}}
          username: ${{secrets.NAME}}
          email: ${{secrets.EMAIL}}
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
            # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
            SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY}}
        with:
            # 注意替换为你的 GitHub 源仓库地址
            source-repo: "git@github.com:Evolution404/Evolution404.github.io.git"
            # 注意替换为你的 Gitee 目标仓库地址
            destination-repo: "git@gitee.com:Evolution404/Evolution404.git"

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@master
        with:
            # 注意替换为你的 Gitee 用户名
            gitee-username: 615598813@qq.com
            # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
            gitee-password: ${{ secrets.GITEE_PASSWORD }}
            # 注意替换为你的 Gitee 仓库
            gitee-repo: Evolution404/Evolution404
